"""añadir columna activo a producto

Revision ID: 22b0fb2bfe2e
Revises: 8442f490a9d3
Create Date: 2025-03-07 10:30:23.996723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b0fb2bfe2e'
down_revision = '8442f490a9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
