"""Agregar campo fecha_registro a Producto

Revision ID: 27b822bfca00
Revises: 
Create Date: 2025-03-08 20:19:42.464431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b822bfca00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
