"""Descripción de los cambios en el modelo

Revision ID: 2d6de1080767
Revises: 642034117c67
Create Date: 2025-03-09 14:26:20.908951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6de1080767'
down_revision = '642034117c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variantes', sa.Text(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_producto_relacionado', type_='foreignkey')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('relacionado_a')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relacionado_a', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_producto_relacionado', 'producto', ['relacionado_a'], ['id'])
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('variantes')

    # ### end Alembic commands ###
