"""Agregar columna relacionado_a a Producto

Revision ID: 642034117c67
Revises: b95ced6716ea
Create Date: 2025-03-09 14:11:47.239092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642034117c67'
down_revision = 'b95ced6716ea'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relacionado_a', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_producto_relacionado', 'producto', ['relacionado_a'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('relacionado_a')

    # ### end Alembic commands ###
