"""Descripción de los cambios

Revision ID: b3d16018d1f0
Revises: 5a5bad28ec88
Create Date: 2025-03-09 15:08:01.620347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d16018d1f0'
down_revision = '5a5bad28ec88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_vendida', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('cantidad_vendida')

    # ### end Alembic commands ###
