"""Descripción del cambio en los modelos

Revision ID: b9df71830653
Revises: b3d16018d1f0
Create Date: 2025-03-09 17:02:42.831387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9df71830653'
down_revision = 'b3d16018d1f0'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False, server_default='1'))  # Valor por defecto
        batch_op.create_foreign_key('fk_producto_categoria', 'categoria', ['categoria_id'], ['id'])  
        batch_op.drop_column('categoria')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_producto_categoria', type_='foreignkey')  # Nombre añadido
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
