"""Corregir nombres de restricciones

Revision ID: f81f9b010e90
Revises: 22b0fb2bfe2e
Create Date: 2025-03-07 13:06:40.316068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81f9b010e90'
down_revision = '22b0fb2bfe2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_producto')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), nullable=False))

    op.create_table('_alembic_tmp_producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
